apps/friendapp/urls.py
from django.conf.urls import url
from . import views
app_name = "friendapp"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^add$', views.add, name='add'),
    url(r'^add/(?P<user_id>\d+)$', views.addFriend, name='addFriend'),
    url(r'^view$', views.view, name='view'),
    url(r'^delete/(?P<user_id>\d+)$', views.delete, name='delete'),
]

apps/loginapp/urls.py
from django.conf.urls import url
from . import views
app_name = "loginapp"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
]

friends/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^', include('apps.loginapp.urls', namespace = "loginapp")),
    url(r'^main/', include('apps.friendapp.urls', namespace = "friendapp")),
]

apps/friendapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..loginapp .models import User
from django.db import models

# Create your models here.

apps/loginapp/models.py
from __future__ import unicode_literals

from django.db import models
import re, bcrypt
from django.contrib import messages
EMAIL_REGEX = re.compile(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")
class UserManager(models.Manager):
    def register(self,postData):
        result = {'status':True, 'error':[]}
        if not postData['first_name'] or postData['first_name'] < 2:
            result['status'] = False
            result['error'].append('First name must be longer than 1 letter')
        if not postData['last_name'] or postData['last_name'] < 2:
            result['status'] = False
            result['error'].append('Last name must be longer than 1 letter')
        if not postData['email'] or not EMAIL_REGEX.match(postData['email']):
            result['status'] = False
            result['error'].append('Must be a valid email')
        if not postData['password'] or postData['password'] < 8:
            result['status'] = False
            result['error'].append('Password must be longer than 8 characters')
        if not postData['confpassword'] or postData['confpassword'] != postData['password']:
            result['status'] = False
            result['error'].append('Passwords must match')
        if result['status'] == True:
            if User.objects.filter(email = postData['email']):
                result['status'] = False
                result['error'].append('User already exist')
            else:
                password = postData['password'].encode('utf-8')
                hashedpw = bcrypt.hashpw(password,bcrypt.gensalt(12))
                User.objects.create(
                    first_name = postData['first_name'],
                    last_name = postData['last_name'],
                    email = postData['email'],
                    password = hashedpw,
                )
        return result
    def login(self,postData, sessionData):
        user = User.objects.filter(email = postData['email'])
        if len(user) > 0:
            hashed = User.objects.get(email = postData['email']).password.encode('utf-8')
            password = postData['password'].encode('utf-8')
            if bcrypt.hashpw(password,hashed) == hashed:
                sessionData['id'] = User.objects.get(email = postData['email']).id
                return True
            else:
                return False

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    friends = models.ManyToManyField('self', related_name='friendof')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = UserManager()

apps/friendapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import User

# Create your views here.
def index(request):
    if 'id' not in request.session:
        return redirect(reverse('loginapp:index'))
    context = {
        "user": User.objects.get(id = request.session['id']),
        "users": User.objects.all().order_by("-created_at")[:3],
    }
    return render(request, "friendapp/index.html", context)
def logout(request):
    request.session.pop('id')
    return redirect(reverse("loginapp:index"))
def view(request):
    if 'id' not in request.session:
        return redirect(reverse('loginapp:index'))
    user = User.objects.get(id=request.session['id'])
    context = {
        "user": User.objects.get(id=request.session['id']),
        "friends": user.friends.all(),
        "count": user.friends.all().count()
    }
    return render(request, 'friendapp/view.html', context)
def add(request):
    if 'id' not in request.session:
        return redirect(reverse('loginapp:index'))
    user = User.objects.get(id = request.session['id'])
    others = User.objects.exclude(id=user.id)
    friends = user.friends.all()
    context = {
        "users": others.exclude(id__in=friends)
    }
    return render(request, 'friendapp/add.html', context)
def delete(request, user_id):
    user = User.objects.get(id = request.session['id'])
    user.friends.remove(User.objects.get(id = user_id))
    return redirect(reverse('friendapp:view'))
def addFriend(request, user_id):
    user = User.objects.get(id = request.session['id'])
    user.friends.add(User.objects.get(id = user_id))
    return redirect(reverse('friendapp:add'))

apps/loginapp/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    return render(request, "loginapp/index.html")
def register(request):
    result = User.objects.register(request.POST)
    if result['status'] == False:
        for error in result['error']:
            messages.error(request,error)
    else:
        messages.success(request,"User created")
    return redirect(reverse("loginapp:index"))
def login(request):
    result = User.objects.login(request.POST, request.session)
    if result == True:
        return redirect("friendapp:index")
    else:
        messages.error(request,"login failed")
        return redirect(reverse("loginapp:index"))

apps/friendapp/templates/friendapp/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Friend</title>
</head>
<body>
    <a href="{% url 'friendapp:index' %}">Go back</a><br>
    <p>Pick a person to add:</p>
    {%for user in users%}
    <a href="{% url 'friendapp:addFriend' user.id%}">{{user.first_name}}</a><br>
    {%endfor%}
</body>
</html>

apps/friendapp/templates/friendapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome {{user.first_name}}</h1>
    <a href="{% url 'friendapp:view' %}">View Friends</a>
    <a href="{% url 'friendapp:add' %}">Add Friends</a>
    <a href="{% url 'friendapp:logout' %}">Logout</a><br>
    <h2>Recent People</h2>      
    {%for user in users%}
        {{user.first_name}} {{user.last_name}} added {{ user.created_at|timesince}} ago <br>
    {%endfor%}
</body>
</html>

apps/friendapp/templates/friendapp/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>View Friends</title>
</head>
<body>
    <a href="{% url 'friendapp:index' %}">Go back</a><br>
    Your Friend count: {{count}}<br>
    {%for friend in friends%}
    {{friend.first_name}} {{friend.last_name}} <a href="{% url 'friendapp:delete' friend.id%}">delete</a><br>
    {%endfor%}
</body>
</html>

apps/loginapp/templates/loginapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Registration</h2>
    <form action = "{% url 'loginapp:register' %}", method = "POST">
        {% csrf_token %}
    First Name: <input type="text" name="first_name" value=""><br>
    Last Name: <input type="text" name="last_name" value=""><br>
    Email: <input type="text" name="email" value=""><br>
    Password: <input type="text" name="password" value=""><br>
    Confirm Password: <input type="text" name="confpassword" value=""><br>
    <input type="submit" name= value="Submit">
    </form>
    <br><br>
    <h2>Login</h2>
    <form action="{% url 'loginapp:login' %}" method="POST">
        {%csrf_token%}
        Email: <input type="text" name="email" value=""><br>
        Password: <input type="text" name="password" value=""><br>
        <input type="submit" name="" value="Submit">
    </form>
    <br><br>
    {%if messages%}
    {%for message in messages%}
    {{message}}
    <br>
    {%endfor%}
    {%endif%}
</body>
</html>